# Generated by Django 5.2.15 on 2026-06-11 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_storesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Delivery', 'Delivery'), ('Utilities', 'Utilities'), ('Salary', 'Salary'), ('Transport', 'Transport'), ('Electricity', 'Electricity'), ('Repair', 'Repair'), ('Other', 'Other')], default='Other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
