# Generated by Django 5.2.15 on 2026-06-12 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='remaining_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BatchExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Transport', 'Transport'), ('Customs', 'Customs'), ('Loading', 'Loading'), ('Tax', 'Tax'), ('Other', 'Other')], default='Other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_expenses', to='shop.purchaseitem')),
            ],
        ),
    ]
