# Generated by Django 5.2.15 on 2026-06-12 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_purchaseitem_batch_number_purchaseitem_remaining_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='shop.purchaseitem')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='shop.saleitem')),
            ],
        ),
    ]
