# Generated by Django 5.2.15 on 2026-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_saleitemallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
