# Generated by Django 5.2.15 on 2026-06-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_purchaseitem_batch_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesetting',
            options={'permissions': [('view_profit_report', 'Can view profit report'), ('view_batch_profit_report', 'Can view batch profit report'), ('view_stock_report', 'Can view stock report'), ('view_dashboard_profit', 'Can view dashboard profit')]},
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='invoice_footer',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='store_name',
        ),
    ]
