# Generated by Django 5.2.15 on 2026-06-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_purchaseitem_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
