# Generated by Django 5.2.15 on 2026-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_purchaseitem_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchexpense',
            name='purchase_item',
        ),
        migrations.AddField(
            model_name='batchexpense',
            name='batch_number',
            field=models.CharField(default='Temp', max_length=50),
        ),
    ]
