# Generated by Django 5.2.15 on 2026-06-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_storesetting_options_and_more'),
        ('shop', '0008_remove_batchexpense_purchase_item_and_more'),
    ]

    operations = [
    ]
