# Generated by Django 5.2.15 on 2026-06-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_merge_20260614_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='currency',
            field=models.CharField(default='AFN', max_length=20),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='invoice_footer',
            field=models.TextField(default='Thank you for your business!'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='store_name',
            field=models.CharField(default='Prime Shop', max_length=150),
        ),
    ]
