# Generated by Django 5.2.15 on 2026-06-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_storesetting_address_storesetting_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.productvariant')),
            ],
        ),
    ]
