# Generated by Django 5.2.15 on 2026-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_stocklocation_purchaseitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
