# Generated by Django 5.2.15 on 2026-06-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_sale_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='shop.sale'),
        ),
    ]
