# Generated by Django 5.2.15 on 2026-06-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_customerpayment_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
