# Generated by Django 5.2.15 on 2026-06-18 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_stockadjustment_target_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='shop_activi_created_f49f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='shop_activi_user_id_371f22_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='shop_activi_action_1b7167_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['model_name'], name='shop_activi_model_n_4781d9_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ip_address'], name='shop_activi_ip_addr_f60dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='batchexpense',
            index=models.Index(fields=['date'], name='shop_batche_date_0f116b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchexpense',
            index=models.Index(fields=['batch_number'], name='shop_batche_batch_n_a9580c_idx'),
        ),
        migrations.AddIndex(
            model_name='batchexpense',
            index=models.Index(fields=['batch_number', 'date'], name='shop_batche_batch_n_4509a4_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['customer', 'date'], name='shop_custom_custome_bfcd70_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['sale'], name='shop_custom_sale_id_3e84bd_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['date'], name='shop_custom_date_45eae1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='shop_expens_date_006ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'date'], name='shop_expens_categor_22ea16_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['date'], name='shop_purcha_date_93dab9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'date'], name='shop_purcha_supplie_de1f09_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['variant'], name='shop_purcha_variant_ca4f57_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['batch_number'], name='shop_purcha_batch_n_e361e9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['location'], name='shop_purcha_locatio_9b01c5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['variant', 'remaining_qty'], name='shop_purcha_variant_008ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date'], name='shop_sale_date_280cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_canceled', 'date'], name='shop_sale_is_canc_b7a795_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'date'], name='shop_sale_custome_4598c0_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_by', 'date'], name='shop_sale_created_bd2853_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='shop_saleit_sale_id_7474f0_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['variant'], name='shop_saleit_variant_9096cd_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitemallocation',
            index=models.Index(fields=['sale_item'], name='shop_saleit_sale_it_04fc89_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitemallocation',
            index=models.Index(fields=['purchase_item'], name='shop_saleit_purchas_d45986_idx'),
        ),
        migrations.AddIndex(
            model_name='salereturn',
            index=models.Index(fields=['date'], name='shop_salere_date_ad5be4_idx'),
        ),
        migrations.AddIndex(
            model_name='salereturn',
            index=models.Index(fields=['sale_item'], name='shop_salere_sale_it_5d31b6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['date'], name='shop_stocka_date_68eaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['variant', 'date'], name='shop_stocka_variant_95138a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['target_batch'], name='shop_stocka_target__d368be_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['location'], name='shop_stocka_locatio_59ca8f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['date'], name='shop_stockt_date_b44ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['variant', 'date'], name='shop_stockt_variant_b537b1_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_location'], name='shop_stockt_from_lo_0af0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['to_location'], name='shop_stockt_to_loca_5ec5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'date'], name='shop_suppli_supplie_677ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['date'], name='shop_suppli_date_9a7295_idx'),
        ),
    ]
