# Generated by Django 5.2.15 on 2026-06-19 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_customer_shop_custom_name_0c18c6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProfitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('purchased_qty', models.PositiveIntegerField(default=0)),
                ('sold_qty', models.PositiveIntegerField(default=0)),
                ('remaining_qty', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('batch_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['batch_number'],
                'indexes': [models.Index(fields=['batch_number'], name='shop_batchp_batch_n_b36afa_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyBusinessSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sale_count', models.PositiveIntegerField(default=0)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('sales_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('general_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('batch_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='shop_dailyb_date_cc038f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUserSalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sale_count', models.PositiveIntegerField(default=0)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('sales_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'user_id'],
                'indexes': [models.Index(fields=['date'], name='shop_dailyu_date_e30988_idx'), models.Index(fields=['user', 'date'], name='shop_dailyu_user_id_2b4f8f_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'user'), name='unique_daily_user_sales_summary')],
            },
        ),
    ]
