# Generated by Django 5.2.15 on 2026-06-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_batchprofitsummary_dailybusinesssummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusersalessummary',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyusersalessummary',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
