# Generated by Django 5.2.15 on 2026-06-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_dailyusersalessummary_outstanding_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybusinesssummary',
            name='paid_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyusersalessummary',
            name='paid_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
