# Generated by Django 5.2.15 on 2026-06-19 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_dailybusinesssummary_paid_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVariantSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sold_qty', models.PositiveIntegerField(default=0)),
                ('sales_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='shop.productvariant')),
            ],
            options={
                'ordering': ['-date', 'variant_id'],
                'indexes': [models.Index(fields=['date'], name='shop_dailyv_date_926e68_idx'), models.Index(fields=['variant', 'date'], name='shop_dailyv_variant_d4b890_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'variant'), name='unique_daily_variant_summary')],
            },
        ),
    ]
