# Generated by Django 5.2.15 on 2026-06-19 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_dailyvariantsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('total_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_at_sale', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payments', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_summary', to='shop.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['balance'], name='shop_custom_balance_f7deca_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaleFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='shop.sale')),
            ],
            options={
                'indexes': [models.Index(fields=['amount_due'], name='shop_salefi_amount__671ada_idx')],
            },
        ),
    ]
