# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0027_customeraccountsummary_salefinancialsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchprofitsummary",
            name="amount_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
