# Generated by Django 5.2.15 on 2026-07-13 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_batchprofitsummary_amount_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='shop_invest_date_d2b7e8_idx'), models.Index(fields=['status', 'date'], name='shop_invest_status_904e9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='shop_invest_name_c17d4a_idx'), models.Index(fields=['is_active'], name='shop_invest_is_acti_065690_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvestorWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='shop.investor')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='shop.investmentround')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['round', 'date'], name='shop_invest_round_i_6b1409_idx'), models.Index(fields=['investor', 'date'], name='shop_invest_investo_4b64b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoundBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='shop.investmentround')),
            ],
            options={
                'ordering': ['batch_number'],
                'indexes': [models.Index(fields=['batch_number'], name='shop_roundb_batch_n_073310_idx'), models.Index(fields=['round', 'batch_number'], name='shop_roundb_round_i_e6d442_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoundInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='shop.investor')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='shop.investmentround')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['round', 'date'], name='shop_roundi_round_i_04466c_idx'), models.Index(fields=['investor', 'date'], name='shop_roundi_investo_40cf4f_idx')],
            },
        ),
    ]
